name: Type Check Code Base
on:
  pull_request: ~
  push:
    branches:
      - main
jobs:
  build:
    name: Type Check Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dependency lazydev
        uses: actions/checkout@v3
        with:
          repository: "folke/lazydev.nvim"
          path: "deps/lazydev.nvim"
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Type Check Code Base
        uses: mrcjkb/lua-typecheck-action@v0
